#!/bin/bash -e
#
# Just put this file in /usr/lib/systemd/system-sleep
# with executable presmissions

NAME=$(basename "$0")
STATUS_DIR="/var/run/nvx/"
STATUS_FILE="$STATUS_DIR"/status

what="$1" # pre/post
action="$2" # suspend/hibernate/etc


function INFO(){
	logger -p info -t "$NAME" "$1"
}


function pre(){
		status=$(/bin/nvx status)
		INFO "saving status $status"

		if [ ! -d "$STATUS_DIR" ]; then
			mkdir -p "$STATUS_DIR"
		fi

		echo "$status" > "$STATUS_FILE"
	}

function post(){
		status=$(/bin/nvx status)

		if [ -s "$STATUS_FILE" ]; then
			status_saved=$(cat "$STATUS_FILE")
		fi
		if [ "$status_saved" != "$status" ]; then
			INFO "restoring $status_saved from $status"
			/bin/nvx "$status_saved"
		fi
	}

case $what in
	pre)
		pre
	;;

	post)
		post
	;;

	*)
		INFO "Unknown command $what/$action"
	;;
esac
